# Generated by Django 3.2.15 on 2026-08-13 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.FloatField(default=1.0, help_text='Lower values force a simpler, more cautious model. Very low values make it visibly worse.', validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1000)], verbose_name='regularisation strength (C)')),
                ('max_iter', models.PositiveIntegerField(default=1000, help_text='How long the fit is allowed to keep improving. Too few and it stops before it has settled.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='maximum iterations')),
                ('solver', models.CharField(choices=[('lbfgs', 'lbfgs'), ('liblinear', 'liblinear'), ('newton-cg', 'newton-cg'), ('saga', 'saga')], default='lbfgs', help_text='The algorithm that does the fitting. On a dataset this small they mostly agree.', max_length=20, verbose_name='solver')),
                ('test_size', models.FloatField(default=0.2, help_text='Share of the 150 flowers kept back for scoring. Larger means a more trustworthy score but less training data.', validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.5)], verbose_name='held-out proportion')),
                ('random_state', models.IntegerField(default=42, help_text='Changing this reshuffles which flowers are used for training and which for scoring.', verbose_name='split seed')),
                ('use_sepal_length', models.BooleanField(default=True, verbose_name='use sepal length')),
                ('use_sepal_width', models.BooleanField(default=True, verbose_name='use sepal width')),
                ('use_petal_length', models.BooleanField(default=True, verbose_name='use petal length')),
                ('use_petal_width', models.BooleanField(default=True, verbose_name='use petal width')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'model configuration',
            },
        ),
    ]
