# Generated by Django 3.2.15 on 2026-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfiguration',
            name='random_state',
            field=models.IntegerField(default=7, help_text='Changing this reshuffles which flowers are used for training and which for scoring.', verbose_name='split seed'),
        ),
    ]
